name: chinese_number
description: Convert Chinese characters into Dart numbers.
version: 1.0.0
homepage: https://github.com/hetu-script/chinese_number

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  characters: ^1.2.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
